### ISSUE TITLE
What are notificationUrl and notificationData?

### ISSUE THREAD

**Issue by riffraff** [bluejeans/api-rest-meetings#3]
There is no documentation as to what either of these two is, or how it is used
I presume these are used for some kind of webhook/http callback mechanic, which is a feature I would like to use, but I am unable to set them in a meeting when creating a meeting object.

**Comment by glenninn** [comment]
hi Gabriele,
  These two fields, in the context of BlueJeans meetings, are unused at the present time.  They are included in the meeting object as part of our standardization of objects between the **Meetings** and **Events** products.

**Comment by riffraff** [comment]
Hey Glenn, thanks for the quick response, I would add this to the docs for clarity, 
Also, hopefully a functionality similar to what I thought this was will eventually find its way into the APIs :)

Have a nice day!

**Comment by glenninn** [comment]
Gabriele,
  I have updated the docs to indicate that these fields are not used.  Thanks for pointing out
