### ISSUE TITLE
Inconsistent/missing information for single meeting history lookup

### ISSUE THREAD

**Issue by riffraff** [bluejeans/api-rest-meetings#6]
Given this endpoint

`/v1/enterprise/{enterprise_id}/meeting_history/{meeting_guid}`

the documentation says 

```
meeting_guid *string(path) | The globally unique identifier (GUID) of the meeting of interest. 
This value is a string which contains the numeric meeting id, followed by a colon, followed by a 128-bit integer number formatted as 5 alphanumeric segments separated by dashes. 
```

So, given for example this meeting 
```
{ 
  id: 18281369,
  uuid: '3c64ac78-27e5-418f-8a92-xxxxxxxxxxxx',
  numericMeetingId: '722632104'
  ...
}
```

it would seem the `meeting_guid` parameter should be `722632104:3c64ac78-27e5-418f-8a92-xxxxxxxxxxxx`

But if I try to look this up, I get a 404. 

If I use the full history listing, I see the meeting, but it reports a different guid

```
"meetingGuid": "722632104:321345-9069044c-6754-4b37-bb0b-xxxxxxxxxxxx"
```
where the part after the ":" has *6* alphanumeric segments separated by dashes, not 5 as the documentation says. 

Sadly, I do not see this larger uuid anywhere in the response when I create a meeting, so how can I know it?

**Comment by glenninn** [comment]
Gabriele,
  you're right.  There are 6 fields.  I will have the doc updated (probably mid next week).

-Glenn

**Comment by riffraff** [comment]
cool, thanks! 
But there is still a problem that this UUID is not in the actual Meeting object, how can I know it? 
Would it be possible to include it in the create Meeting response?
